version: 1
disable_existing_loggers: False

formatters:
  simple:
    format: "%(asctime)s | %(name)s | %(levelname)s | PID: %(process)d | %(filename)s:%(lineno)d | %(funcName)s | %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG 
    formatter: simple
    stream: ext://sys.stdout

loggers:
  smart_pokedex:
    level: DEBUG  
    handlers: [console]
    propagate: no
  tensorflow:
    level: CRITICAL
    handlers: [console]
    propagate: no
  absl:
    level: CRITICAL
    handlers: [console]
    propagate: no

root:
  level: WARNING
  handlers: [console]